---
- hosts: localhost
  connection: local

  tasks:
    - name: Get the latest Docker image tag
      ansible.builtin.shell:
        cmd: "wsl docker pull alrakhami/regiapp:latest"
      ignore_errors: yes
      register: latest_image_pull

    - set_fact:
        image_tag: "alrakhami/regiapp:latest"

    - name: Start container 1
      ansible.builtin.shell:
        cmd: "wsl docker run -d --name regi_app1 -p 8085:8080 {{ image_tag }}"

    - name: Start container 2
      ansible.builtin.shell:
        cmd: "wsl docker run -d --name regi_app2 -p 8086:8080 {{ image_tag }}"

